### ISSUE TITLE
create reusable button component

### ISSUE THREAD

**Issue by dylanreedx** [carbondesigned/CityCyclery#2]
We want a few button variants we can easily use and change if we need.

The example code might need to be touched on, but a quick explanation is that we can use CVA which can create variants (with Tailwind is perfect). It's easy to add on other variants if needed.

## todo
- [ ] install CVA
- [ ] install Phosphor Ccons
- [ ] create button file
- [ ] update colors/theme to match our system

```tsx
import { cva, VariantProps } from 'class-variance-authority';
import Link from 'next/link';

const buttonStyle = cva(
  'py-3 px-5 rounded-full flex-row items-center justify-evenly',
  {
    variants: {
      variant: {
        primary: 'bg-primaryWhite text-primaryDark',
        secondary: 'bg-secondaryDark border-1 border-tertiaryDark',
        menu: 'bg-transparent rounded-none border-t-2 border-tertiaryDark',
        danger: 'bg-transparent rounded-none border-t-2 border-tertiaryDark',
        ghost: 'bg-transparent py-0',
      },
    },
  }
);

interface ButtonProps
  extends React.AnchorHTMLAttributes<HTMLAnchorElement>,
    VariantProps<typeof buttonStyle>,
    VariantProps<typeof buttonTextStyle> {
  children: React.ReactNode;
  variant: 'primary' | 'secondary' | 'menu' | 'danger' | 'ghost';
  icon?: React.ReactNode;
  textSize?: 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl';
}

export default function Button({
  children,
  variant,
  icon,
  textSize,
  ...props
}: ButtonProps) {
  return (
    <Link href={href} as={as} passHref>
      <a {...props} className={buttonStyle({ variant })}>
        {icon && icon}
        <span className={buttonTextStyle({ variant, textSize })}>{children}</span>
      </a>
    </Link>
  );
}
```
```tsx
// how our button can be used
<Button href="#" variant='primary' icon={<Barbell weight='fill' />}>Click Here</Button>
```
